name: Run Chaos Toolkit Experiment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  chaos-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Chaos Toolkit
        run: |
          python -m pip install --upgrade pip
          pip install chaostoolkit chaostoolkit-aws

      - name: Run Chaos Toolkit Experiment
        run: |
          cat <<EOF > ec2-chaos-experiment.json
          {
            "version": "1.0.0",
            "title": "EC2 Instance Failure Test",
            "description": "Check if EC2 instance is running and then stop it to simulate a failure.",
            "steady-state-hypothesis": {
              "title": "EC2 Instance is Running",
              "probes": [
                {
                  "type": "probe",
                  "name": "check_instance_status",
                  "provider": {
                    "type": "python",
                    "module": "chaosaws.ec2.probes",
                    "func": "instance_status",
                    "arguments": {
                      "instance_ids": ["i-01f2da831aa5ac9e8"],
                      "region": "eu-west-1"
                    }
                  },
                  "tolerance": {
                    "type": "jsonpath",
                    "path": "$.InstanceStatuses[*].InstanceState.Name",
                    "expect": "running"
                  }
                }
              ]
            },
            "method": [
              {
                "type": "action",
                "name": "stop_instance",
                "provider": {
                  "type": "python",
                  "module": "chaosaws.ec2.actions",
                  "func": "stop_instances",
                  "arguments": {
                    "instance_ids": ["i-01f2da831aa5ac9e8"],
                    "region": "eu-west-1"
                  }
                }
              }
            ],
            "rollbacks": [
              {
                "type": "action",
                "name": "start_instance",
                "provider": {
                  "type": "python",
                  "module": "chaosaws.ec2.actions",
                  "func": "start_instances",
                  "arguments": {
                    "instance_ids": ["i-01f2da831aa5ac9e8"],
                    "region": "eu-west-1"
                  }
                }
              }
            ]
          }
          EOF

          chaos run ec2-chaos-experiment.json
